import pyrubi



bot = pyrubi.Client("bogggg")
# لینک گپ
link = input("enter link:")

guid = bot.join_chat(link)["group"]["group_guid"]

print(guid)
for  i in range(5):
    
    print(bot.send_text(guid, "@@boggap@@(u0FGbWD0fdcda6aa41534a4e5fff7568)‌ ‌ @@boggap@@(u0FGbWD0fdcda6aa41534a4e5fff7568)'/n)"))
    bot.send_text(guid,"SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.SW.")
bot.leave_chat(guid)
